# Generated by jig from examples\feature_showcase.jig. Do not edit.
from __future__ import annotations
import jig_runtime as __jig__
from jig_runtime import Ctx, fixed_ctx
from jig_runtime import Nothing, Option, Some
from jig_runtime import replace
from jig_runtime import Err, Ok, Result
UserId = __jig__.newtype('UserId', int)
Score = __jig__.newtype('Score', int)

@__jig__.record
class Player:
    id: UserId
    name: str
    score: Score
    active: bool

class GameError(__jig__.Enum):
    PLAYER_NOT_FOUND = 'PLAYER_NOT_FOUND'
    INVALID_SCORE = 'INVALID_SCORE'
    GAME_OVER = 'GAME_OVER'
ALICE: Player = Player(id=UserId(1), name='Alice', score=Score(100), active=True)

@__jig__.fn(requires=[('points >= Score(0)', lambda player, points: points >= Score(0))], ensures=[], effects=())
def add_score(player: Player, points: Score) -> Player:
    """Add points to a player's score. Demonstrates newtypes, records."""
    new_score = player.score + points
    return replace(player, score=new_score)

@__jig__.fn(requires=[], ensures=[], effects=())
def find_player(players: list[Player], id: UserId) -> Option[Player]:
    """Find a player by ID. Demonstrates Option."""
    for p in players:
        if p.id == id:
            return Some(p)
    return Nothing

@__jig__.fn(requires=[], ensures=[], effects=('log', 'time'))
def log_score(ctx: Ctx, player: Player) -> str:
    """Log a player's score. Demonstrates effects and Ctx."""
    ctx.log.info(f'{player.name} has {player.score} points')
    timestamp = ctx.clock.now()
    return f'logged at {timestamp}'

@__jig__.fn(requires=[], ensures=[], effects=())
def describe_error(error: GameError) -> str:
    """Convert error to message. Demonstrates exhaustive enum matching."""
    match error:
        case GameError.PLAYER_NOT_FOUND:
            return 'Player not found'
        case GameError.INVALID_SCORE:
            return 'Invalid score'
        case GameError.GAME_OVER:
            return 'Game over'
