# Generated by jig from examples\test_math.jig. Do not edit.
from __future__ import annotations
import jig_runtime as __jig__
from jig_runtime import Err, Ok, Result
Score = __jig__.newtype('Score', int)

class MathError(__jig__.Enum):
    DIVIDE_BY_ZERO = 'DIVIDE_BY_ZERO'
    NEGATIVE_INPUT = 'NEGATIVE_INPUT'

@__jig__.fn(requires=[], ensures=[], effects=())
def divide(a: int, b: int) -> Result[int, MathError]:
    """Divide two numbers."""
    if b == 0:
        return Err(MathError.DIVIDE_BY_ZERO)
    return Ok(a / b)

@__jig__.fn(requires=[], ensures=[], effects=())
def add_scores(x: Score, y: Score) -> Score:
    """Add two scores together."""
    return Score(x + y)
